# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_class_name', models.CharField(max_length=100)),
                ('document_class_file', models.FileField(upload_to='tex')),
            ],
        ),
    ]
