# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_documentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.DocumentClass'),
            preserve_default=False,
        ),
    ]
