# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_document_document_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='department_addressed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_class',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user_submitted',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentClass',
        ),
    ]
