# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20151214_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('civil', 'Civilian')], default='civil', max_length=5),
        ),
    ]
