# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_user_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_field_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='documentclass',
            name='document_fields',
            field=models.ManyToManyField(to='documents.DocumentFields'),
        ),
    ]
