# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_department_addressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department_addressed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.Department'),
            preserve_default=False,
        ),
    ]
